### ISSUE TITLE
Handling input/output waveguide in view

### ISSUE THREAD

**Issue by mabuni1998** [qojulia/WaveguideQED.jl#25]
I have now implemented a basis for containing twophoton states in input and output waveguides. The new data structure can be viewed via the function:

https://github.com/mabuni1998/CavityWaveguide/blob/36d18ef36dc229c49a820f470cea5ed4aa910097/src/view.jl#L120-L140

Here, the argument `type` determines which part of the state you view. For example, `type=:input` returns a view of the two-photon input state. Likewise, `type=:output` returns a view of the two-photon output state, and `type=:inputoutput` gives the one-photon in input one photon in output state. `type=:singlewaveguide` is the standard used when you have only a single waveguide. I know that I could define TwoPhotonView{type} and then have a specialized function for each of the scenarios but for now, I'm just using the if statements here. I'm working on documentation, and the purpose of this issue is not to discuss the rest of the implementation but to discuss specifically how the view is made more friendly to use (if possible). For an example where I use the view, see:
https://github.com/mabuni1998/CavityWaveguide/blob/36d18ef36dc229c49a820f470cea5ed4aa910097/Examples/lodahl_fig2%20IO.jl#L49

Is this the typical way of having options in a function? Sometimes in python you would use string names instead so that the type would be: `type="input"` and you would dispatch from here. Is there a typical way of doing it in Julia other than the way I did it @Krastanov ?

**Comment by Krastanov** [comment]
Using symbols instead of strings is already much better than what python does.

But you might be able to simplify even more:

Is there something in the Ket type that tells you which view should be created?  Is the basis always of a certain type. Maybe something that would help me answer the question is to show a couple of examples of when each one of these is used (and the exact `typeof(...)` for the ket argument).

Unrelated: We might need to worry about type stability here. This function is not type stable. If it is used often in inner loops, that can be a problem. One way to solve this, completely unrelated to the rest of your code, is to use `Val` types. E.g. `Val{:output}()` instead of `:output`.

**Comment by Krastanov** [comment]
But the short answer is, unless there is something in the type of the `ψ` input argument that you can use (or property of the instance even), then yes, your approach is great (unless type stability is a worry).

**Comment by mabuni1998** [comment]
Ahhh, this is great! I was just about to write an issue about how to handle the type of some specific operator which is closely related to how we would do it for a Ket. The problem is unrelated to here, and for the most part, we can't dispatch on the type of Ket. The idea of the type argument is for the user to choose what type of excitation they want. Do they want two photons in the left or the right waveguide (input or output), or do they want an "entangled" state with one photon in the left or one photon in the right? In all of these cases,  typeof(Ket) is something long and complicated where on of the bases is `InputOutputWaveguideBasis` . 

This brings us to the question about which I was about to make an issue.  I want a specialized expect(operator,psi) function that, when it gets an operator which has a WaveguideOperator in it, loops over all times. This is easy to do if the input operator is just of type `WaveguideOperator`; then we could do something like:

```
function expect(operator::WaveguideOperator,psi::Ket)
    **DO LOOP**
end
```

But often, the operator is of type LazyTensor since we might have another quantum system. As an example, consider a waveguide with a cavity, and we are interested in the total population of the waveguide:
```
times = 0.0:0.1:10
bw = WaveguideBasis(2,times)
bc = FockBasis(2)
wd = create(bw) ⊗ identityoperator(bc)
w = destroy(bw) ⊗  identityoperator(bc)
nw = LazyProduct(wd,w)
```

Now typeof(w) gives:

```
LazyTensor{CompositeBasis{Vector{Int64}, Tuple{WaveguideBasis{2}, FockBasis{Int64}}}, CompositeBasis{Vector{Int64}, Tuple{WaveguideBasis{2}, FockBasis{Int64}}}, ComplexF64, Vector{Int64}, Tuple{WaveguideDestroy{WaveguideBasis{2}, WaveguideBasis{2}, 2}, Operator{FockBasis{Int64}, FockBasis{Int64}, SparseArrays.SparseMatrixCSC{ComplexF64, Int64}}}}
```

It's clear that if we somehow can do a specialized function where it dispatches based on whether the basis of the operator includes a WaveguideBasis, then we would be good. My question is how? How do we pick out the part of CompositeBasis{Vector{Int64}, Tuple{WaveguideBasis{2}, FockBasis{Int64}}} where it says `Tuple{WaveguideBasis{2}, FockBasis{Int64}}}` and ask "if this tuple includes WaveguideBasis then do this"?

Btw, in the end I want to do something similar with nw which has the type: 

```
LazyProduct{CompositeBasis{Vector{Int64}, Tuple{WaveguideBasis{2}, FockBasis{Int64}}}, CompositeBasis{Vector{Int64}, Tuple{WaveguideBasis{2}, FockBasis{Int64}}}, Int64, Tuple{LazyTensor{CompositeBasis{Vector{Int64}, Tuple{WaveguideBasis{2}, FockBasis{Int64}}}, CompositeBasis{Vector{Int64}, Tuple{WaveguideBasis{2}, FockBasis{Int64}}}, ComplexF64, Vector{Int64}, Tuple{WaveguideCreate{WaveguideBasis{2}, WaveguideBasis{2}, 2}, Operator{FockBasis{Int64}, FockBasis{Int64}, SparseArrays.SparseMatrixCSC{ComplexF64, Int64}}}}, LazyTensor{CompositeBasis{Vector{Int64}, Tuple{WaveguideBasis{2}, FockBasis{Int64}}}, CompositeBasis{Vector{Int64}, Tuple{WaveguideBasis{2}, FockBasis{Int64}}}, ComplexF64, Vector{Int64}, Tuple{WaveguideDestroy{WaveguideBasis{2}, WaveguideBasis{2}, 2}, Operator{FockBasis{Int64}, FockBasis{Int64}, SparseArrays.SparseMatrixCSC{ComplexF64, Int64}}}}}, Tuple{Ket{CompositeBasis{Vector{Int64}, Tuple{WaveguideBasis{2}, FockBasis{Int64}}}, Vector{ComplexF64}}}, Tuple{Bra{CompositeBasis{Vector{Int64}, Tuple{WaveguideBasis{2}, FockBasis{Int64}}}, Vector{ComplexF64}}}}
```

Again we should be able to just specialize on the `CompositeBasis{Vector{Int64}, Tuple{WaveguideBasis{2}, FockBasis{Int64}}}` part.

I hope my question makes sense.
