### ISSUE TITLE
Typos in README

### ISSUE THREAD

**Issue by phantomlsh** [qojulia/WaveguideQED.jl#41]
Thank you very much for the package!

There are some typos in the code demo in README.

First, the second line below should be `wd` instead of `w`
```julia
# original
w =  destroy(bw)
w =  create(bw)
```

Second, the first line below should be `TwoPhotonView` instead of `view_twophoton`
```julia
# original
ψ_double = view_twophoton(ψ);
using PyPlot
fig,ax = subplots(1,1,figsize=(9,4.5))
plot_twophoton!(ax,ψ_double,times)
```

Finally, would you offer a version of the plot using the `Plots` package, as the `PyPlot` package causes some extra trouble, especially in the non-interactive scenario? One of the potential solutions for the README example might be:

```julia
using Plots
twophotonstate = ψ_double
cnt1 = contourf(times, times, abs.(twophotonstate).^2, levels=10, color=:turbo, aspect_ratio=:equal, size=(400,400))
```

I would be very happy to submit a Pull Request for these improvements if a PR is encouraged.

**Comment by Krastanov** [comment]
Thanks for the report! Yes, PR are always encouraged :grin:

**Comment by phantomlsh** [comment]
Cool, I will submit a PR then.
